export const blink: string
export const bounce: string
export const darkBackground: string
export const darkLevel1: string
export const darkLevel2: string
export const darkPaper: string
export const darkPrimary200: string
export const darkPrimary800: string
export const darkPrimaryDark: string
export const darkPrimaryLight: string
export const darkPrimaryMain: string
export const darkSecondary200: string
export const darkSecondary800: string
export const darkSecondaryDark: string
export const darkSecondaryLight: string
export const darkSecondaryMain: string
export const darkTextPrimary: string
export const darkTextSecondary: string
export const darkTextTitle: string
export const errorDark: string
export const errorLight: string
export const errorMain: string
export const fullscreen: string
export const grey100: string
export const grey200: string
export const grey300: string
export const grey50: string
export const grey500: string
export const grey600: string
export const grey700: string
export const grey900: string
export const orangeDark: string
export const orangeLight: string
export const orangeMain: string
export const paper: string
export const primary200: string
export const primary800: string
export const primaryDark: string
export const primaryLight: string
export const primaryMain: string
export const ps: string
export const psActiveY: string
export const psClicking: string
export const psRailX: string
export const psRailY: string
export const psScrollingX: string
export const psScrollingY: string
export const psThumbY: string
export const reactImagesBlanket: string
export const scrollbarContainer: string
export const secondary200: string
export const secondary800: string
export const secondaryDark: string
export const secondaryLight: string
export const secondaryMain: string
export const slideX: string
export const slideY: string
export const success200: string
export const successDark: string
export const successLight: string
export const successMain: string
export const warningDark: string
export const warningLight: string
export const warningMain: string
export const wings: string
